title: Jacky Liang
baseurl: /
google_analytics: UA-72166690-1
theme: jekyll-theme-minimal

# urls
urls:
    linkedin: "https://www.linkedin.com/in/jackyliang42"
    github: "https://www.github.com/jacky-liang"
    scholar: "https://scholar.google.com/citations?user=K29Sv1EAAAAJ&hl=en&oi=ao"
    twitter: "https://twitter.com/jackyliang42"